import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {spawn} from 'node:child_process';
import os from 'node:os';
import {fileURLToPath} from 'node:url';
const here=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const data=await fs.mkdtemp(path.join(os.tmpdir(),'career-ai-ui-')),port=4322,url=`http://127.0.0.1:${port}`;
const fixture=path.join(here,'test/mock-codex.mjs');await fs.chmod(fixture,0o755);
const server=spawn(process.execPath,['server.mjs'],{cwd:here,env:{...process.env,PORT:String(port),STUDIO_DATA:data,STUDIO_CODEX_BIN:fixture},stdio:['ignore','pipe','pipe']});
let stderr='';server.stderr.on('data',x=>stderr+=x);await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('exit',()=>reject(Error(stderr)));});
const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1512,height:1050}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));await fs.mkdir(path.join(here,'.test-data'),{recursive:true});
try{
 await page.goto(url);const frame=page.frameLocator('iframe');await frame.locator('h1').first().waitFor();
 await page.getByRole('button',{name:'새 문서',exact:true}).click();await page.getByLabel('문서 이름').fill('Codex 샘플 검증');await page.getByRole('button',{name:'만들기',exact:true}).click();
 await frame.locator('h1').filter({hasText:'새로운 이야기'}).waitFor();await frame.locator('h1').fill('테스트 전');await frame.locator('h1').click();
 await page.getByRole('button',{name:'✦ Codex 채팅',exact:true}).click();await page.getByRole('button',{name:'Codex 연결',exact:true}).click();
 await page.getByLabel('Codex 모델').selectOption('test-model');await page.getByLabel('추론 강도').selectOption('low');
 await page.getByLabel('요청문과 선택 범위를 OpenAI로 전송하는 데 동의').check();
 const send=async(text)=>{await page.getByLabel('Codex 요청',{exact:true}).fill(text);await page.getByRole('button',{name:'보내기',exact:true}).click();};
 await send('샘플 제목 변경');await page.getByRole('button',{name:'검토 후 적용',exact:true}).waitFor();assert.equal(await frame.locator('h1').innerText(),'테스트 전');
 await page.screenshot({path:path.join(here,'.test-data/codex-chat.png')});
 await page.getByRole('button',{name:'검토 후 적용',exact:true}).click();const dialog=page.getByRole('dialog',{name:'AI 수정안 검토'});
 await page.screenshot({path:path.join(here,'.test-data/codex-diff.png')});await dialog.getByRole('button',{name:'확인하고 적용',exact:true}).click();await dialog.waitFor({state:'hidden'});
 assert.equal(await frame.locator('h1').innerText(),'테스트 후');await page.getByRole('button',{name:'실행 취소',exact:true}).click();assert.equal(await frame.locator('h1').innerText(),'테스트 전');
 await page.getByRole('button',{name:'다시 실행',exact:true}).click();assert.equal(await frame.locator('h1').innerText(),'테스트 후');
 console.log('PASS: chatbot model/effort selection, explicit consent, review, apply, undo/redo');
 await frame.locator('h1').fill('테스트 전');await frame.locator('h1').click();await send('두 번째 샘플 변경');await page.getByRole('button',{name:'검토 후 적용',exact:true}).waitFor();
 await frame.locator('h1').fill('내가 직접 고친 제목');await page.getByRole('button',{name:'검토 후 적용',exact:true}).click();await dialog.getByRole('button',{name:'확인하고 적용',exact:true}).click();
 await page.locator('.ai-error').filter({hasText:'변경됐습니다'}).waitFor({state:'attached'});assert.equal(await frame.locator('h1').innerText(),'내가 직접 고친 제목');await dialog.getByRole('button',{name:'닫기',exact:true}).click();
 await page.getByRole('button',{name:'수정안 취소',exact:true}).click();await page.getByText('취소한 수정안',{exact:true}).waitFor();
 console.log('PASS: stale proposals cannot overwrite manual edits');
 await page.getByLabel('AI 동작').selectOption('ask');await send('문구에 대한 질문');await page.getByText('샘플 문구에 대한 답변입니다.',{exact:true}).waitFor();assert.equal(await frame.locator('h1').innerText(),'내가 직접 고친 제목');
 await send('slow');await page.getByRole('button',{name:'중단',exact:true}).click();await page.locator('.ai-running').waitFor({state:'hidden'});
 await page.reload();await frame.locator('h1').filter({hasText:'내가 직접 고친 제목'}).waitFor();await page.getByRole('button',{name:'✦ Codex 채팅',exact:true}).click();await page.getByText('샘플 문구에 대한 답변입니다.',{exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Codex 연결',exact:true}).count(),1);
 await page.getByRole('button',{name:'Codex 연결',exact:true}).click();await page.getByLabel('Codex 모델').waitFor();await page.getByLabel('AI 요청 범위').selectOption('document');await page.getByLabel('요청문과 선택 범위를 OpenAI로 전송하는 데 동의').check();
 await send('css');await page.getByRole('button',{name:'검토 후 적용',exact:true}).click();await dialog.getByRole('button',{name:'확인하고 적용',exact:true}).click();await dialog.waitFor({state:'hidden'});
 assert.equal(await frame.locator('h1').evaluate(n=>getComputedStyle(n).color),'rgb(1, 2, 3)');await page.getByRole('button',{name:'실행 취소',exact:true}).click();assert.equal(await frame.locator('h1').evaluate(n=>getComputedStyle(n).color),'rgb(32, 40, 50)');
 console.log('PASS: document head CSS applies to the live preview and supports undo');
 const config=await (await page.request.get(url+'/api/config')).json();assert.equal((await page.request.get(url+'/api/ai/history?docId=resume--document')).status(),403);
 assert.equal((await page.request.post(url+'/api/ai/request',{data:{consent:false},headers:{'X-Studio-Token':config.token}})).status(),400);
 await page.setViewportSize({width:1100,height:800});await page.screenshot({path:path.join(here,'.test-data/codex-compact.png')});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);console.log('PASS: question-only, cancellation, local chat history, explicit reconnect, token checks and compact layout');
}catch(e){await page.screenshot({path:path.join(here,'.test-data/codex-failure.png')});console.error(errors,stderr);throw e;}
finally{await browser.close();server.kill('SIGTERM');}
